fixtures:
    forge_modules:
        stdlib: "puppetlabs/stdlib"
        firewall: "puppetlabs/firewall"
        limits: "puppetlabs/limits"
        concat: "puppetlabs/concat"
        ntp: "puppetlabs/ntp"
        selinux: "puppet/selinux"
        augeasproviders_core: "herculesteam/augeasproviders_core"
        augeasproviders_grub: "herculesteam/augeasproviders_grub"
        sysctl: "thias/sysctl"
        auditd: "kemra102/auditd"
    symlinks:
        toughen: "#{source_dir}"

